### ISSUE TITLE
python 3.12 compatibility issue

### ISSUE THREAD

**Issue by kosli** [VerenigingCampusKabel/python-sepa#8]
is it possible that this module doesn't work with python 3.12? 
```
File "/home/xxx/beancount/venv-beancount/lib/python3.12/site-packages/sepa/messages/__init__.py", line 12, in <module>
    module = loader.find_module(name).load_module(name)
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```

**Comment by manatlan** [comment]
same !

but changed "venv\Lib\site-packages\sepa\messages\__init__.py"

line :
```
    module = loader.find_module(name).load_module(name)
```

to :
 
```
    module = __import__(name)
```

but **ModuleNotFoundError: No module named 'camt'**

**Comment by JeorenB** [comment]
same!
 It worked with python 3.11, but not with 3.12 and 3.13. I don't expect it with 3.14, which will be pre-released on January 10th.

**Comment by DanielleHuisman** [comment]
This project is not maintained anymore.

**Comment by JeorenB** [comment]
I was afraid so, thanks for the answer.


Greetings,

Op ma 3 mrt 2025, 13:35 schreef Daniëlle Huisman ***@***.***>:
